version: "3"
services:
  webserver:
    image: nginx
    container_name: webserver
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
  worker:
    build: .
    container_name: worker
    volumes:
      - ./scripts:/scripts
    command: tail -f /dev/null
